parameters:
   gamma_logger_enabled: true
   gamma_logger_slow_time_limit: 1000

services:
    gamma.listener.requestresponse.stopwatch.slow:
        class: Gamma\ApiLogger\Listener\TrackDurationListener
        arguments: [ @gamma.logger.stopwatch.slow]
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    gamma.listener.requestresponse.stopwatch:
        class: Gamma\ApiLogger\Listener\TrackDurationListener
        arguments: [ @gamma.logger.stopwatch]
        tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    symfony.stopwatch.service:
        class: Symfony\Component\Stopwatch\Stopwatch

    gamma.logger.stopwatch:
        class: Gamma\ApiLogger\Service\LoggerStopwatch
        arguments: [ @symfony.stopwatch.service, @logger, %gamma_logger_enabled% ]
        tags:
            - { name: monolog.logger, channel: api }

    gamma.logger.stopwatch.slow:
        class: Gamma\Framework\Service\LoggerStopwatchSlow
        arguments: [ @symfony.stopwatch.service, @logger, %stopwatch_enable%,  %gamma_logger_slow_time_limit%]
        tags:
            - { name: monolog.logger, channel: api_slow }